name: TikTok Turbo Updater

on:
  schedule:
    - cron: '*/10 * * * *' # Jalan tiap 10 menit (Paling Cepat yang Aman)
  push: # Jalan tiap kali ada edit file
  workflow_dispatch: # Tombol manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Siapkan Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Alat
        run: pip install requests

      - name: Jalankan Scraper
        run: python update_links.py

      - name: Simpan Data
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@noreply.com"
          git add vl_data.json
          git commit -m "Update: $(date)" || exit 0
          git push
